//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deneme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedBack_Info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FeedBack_Info()
        {
            this.FeedBack_IMG = new HashSet<FeedBack_IMG>();
            this.FeedBack_Point = new HashSet<FeedBack_Point>();
            this.FeedBack_Description = new HashSet<FeedBack_Description>();
        }
    
        public int FeedBackID { get; set; }
        public int ProductID { get; set; }
        public int UserID { get; set; }
        public decimal Price { get; set; }
        public Nullable<System.DateTime> BuyDate { get; set; }
        public Nullable<System.DateTime> FormationDay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeedBack_IMG> FeedBack_IMG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeedBack_Point> FeedBack_Point { get; set; }
        public virtual Product Product { get; set; }
        public virtual User_PI User_PI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeedBack_Description> FeedBack_Description { get; set; }
    }
}
