//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deneme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedBack_Point
    {
        public Nullable<int> FeedBackID { get; set; }
        public Nullable<int> Dayaniklilik { get; set; }
        public Nullable<int> FiyatPerformans { get; set; }
        public Nullable<int> Kalite { get; set; }
        public Nullable<int> DisGörünüs { get; set; }
        public Nullable<int> KullanimKolayligi { get; set; }
        public int Point_ID { get; set; }
    
        public virtual FeedBack_Info FeedBack_Info { get; set; }
    }
}
