//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deneme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Com
    {
        public Nullable<int> ID { get; set; }
        public string Mail { get; set; }
        public long Phone { get; set; }
        public string Adress { get; set; }
        public int Com_ID { get; set; }
        public string Password { get; set; }
    
        public virtual User_PI User_PI { get; set; }
    }
}
