//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deneme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vFeedBack
    {
        public int Bildirim_Numarası { get; set; }
        public string Kullanıcı_Adı { get; set; }
        public string Ürün_İsmi { get; set; }
        public int Company { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    }
}
