//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deneme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vProducts
    {
        public long RowId { get; set; }
        public int ID { get; set; }
        public string Name { get; set; }
        public string SubName { get; set; }
        public Nullable<decimal> SellPrice { get; set; }
        public string CompanyName { get; set; }
    }
}
